env: prod
namespace: default
restartPolicy: OnFailure

image:
    repository: ysde/docker-grafana-backup-tool
    tag: 1.2.3
    pullPolicy: IfNotPresent

crons:
    "0":
        name: mon-fri-cron
        schedule: "0 */2 * * 1-5"
    "1":
        name: daily-cron
        schedule: "0 18 * * *"
    "2":
        name: weekly-cron
        schedule: "0 18 * * FRI"

environmentVariables:
    GRAFANA_TOKEN: "eyJrIjoiQlRuZWlTNzVjTnY1Z3dDZU5FMDUwMFdMUzJNOExrOVIiLCJuIjoiYmFja3VwIiwiaWQiOjF9"
    GRAFANA_URL: http://192.168.56.10:3000
    GRAFANA_ADMIN_ACCOUNT: admin
    GRAFANA_ADMIN_PASSWORD: admin
    VERIFY_SSL: False
    AWS_S3_BUCKET_NAME: "grafana-backup-poc"
    AWS_DEFAULT_REGION: "us-east-1"
    AWS_SECRET_ACCESS_KEY: "secret key"
    AWS_ACCESS_KEY_ID: "access key"
