env: dev  
restartPolicy: OnFailure
image:
    repository: ysde/docker-grafana-backup-tool
    tag: 1.2.3
    pullPolicy: IfNotPresent 
service: 
    internalPort: 8028
crons:
    "0":
    name: mon-fri-cron
    schedule: "0 6 * * 1-5"
    "1":
    name: daily-cron
    schedule: "0 8 * * *" 
    "2":
    name: weekly-cron
    schedule: "0 20 * * FRI" 
