{{- range $job, $val := .Values.cronjob.crons }}
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  namespace: {{ .Values.env }}
  name: {{ .name }}
  labels:
    draft: {{ default "draft-app" $.Values.draft }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  schedule: {{ .schedule | quote }}
  successfulJobsHistoryLimit: 0 
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            draft: {{ default "draft-app" $.Values.draft }}
            app: {{ .name }}
        spec:       
          containers:
          - name: {{ .name }}
            image: "{{ $.Values.image.repository }}:{{ $.Values.image.tag }}"
            imagePullPolicy: {{ $.Values.image.pullPolicy }} 
          restartPolicy: {{ $.Values.restartPolicy }}
---
{{- end}}