{{- range $key, $value := .Values.crons }}
apiVersion: batch/v1
kind: CronJob
metadata:
  namespace: {{ $.Values.namespace }}
  name: {{ .name }}
  labels:
    job-name: {{ .name }}
    chart: "{{ $.Chart.Name }}-{{ $.Chart.Version | replace "+" "_" }}"
    release: {{ $.Chart.Version }}
spec:
  schedule: {{ .schedule }}
  successfulJobsHistoryLimit: 0
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            job-name: {{ .name }}
            release: {{ $.Chart.Version }}
        spec:
          containers:
          - name: {{ .name }}
            image: "{{ $.Values.image.repository }}:{{ $.Values.image.tag }}"
            env:
            {{- range $k, $v := $.Values.environmentVariables }}
              - name: {{ $k }}
                value: {{ $v | quote }}
              {{- end }}
            imagePullPolicy: {{ $.Values.image.pullPolicy }}
          restartPolicy: {{ $.Values.restartPolicy }}
---
{{- end}}