{{- range $key, $value := .Values.crons }}
apiVersion: batch/v1
kind: CronJob
metadata:
  namespace: {{ $.Values.namespace }}
  name: {{ .name }}
  labels:
    job-name: {{ .name }}
    chart: "{{ $.Chart.Name }}-{{ $.Chart.Version | replace "+" "_" }}"
spec:
  schedule: {{ .schedule }}
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: busybox:1.28
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - date; echo Hello from the Kubernetes cluster
          restartPolicy: OnFailure
---
{{- end}}